"""Add telefono column to users

Revision ID: 73623af5bbaf
Revises: 2cd6934354cd
Create Date: 2025-04-02 23:22:07.823828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73623af5bbaf'
down_revision: Union[str, None] = '2cd6934354cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('celular', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_celular'), 'users', ['celular'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_celular'), table_name='users')
    op.drop_column('users', 'celular')
    # ### end Alembic commands ###
