"""add pagado field to Sale

Revision ID: a49890441bae
Revises: 73623af5bbaf
Create Date: 2025-04-08 06:06:51.182651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a49890441bae'
down_revision: Union[str, None] = '73623af5bbaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('pagado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'pagado')
    # ### end Alembic commands ###
