"""add full relationships

Revision ID: 2cd6934354cd
Revises: f4ac2e26b7df
Create Date: 2025-02-23 15:35:40.456695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd6934354cd'
down_revision: Union[str, None] = 'f4ac2e26b7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineOfSale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('numeroDeLinea', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineOfSale_id'), 'lineOfSale', ['id'], unique=False)
    op.add_column('sales', sa.Column('medioPago', sa.String(), nullable=True))
    op.add_column('users', sa.Column('apellido', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_apellido'), 'users', ['apellido'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_apellido'), table_name='users')
    op.drop_column('users', 'apellido')
    op.drop_column('sales', 'medioPago')
    op.drop_index(op.f('ix_lineOfSale_id'), table_name='lineOfSale')
    op.drop_table('lineOfSale')
    # ### end Alembic commands ###
