"""Create sales table

Revision ID: 45444fd36e63
Revises: 09316dc93882
Create Date: 2025-02-21 16:53:43.666301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45444fd36e63'
down_revision: Union[str, None] = '09316dc93882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity_product', sa.Integer(), nullable=True),
    sa.Column('observation', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('order_confirmed', sa.Boolean(), nullable=True),
    sa.Column('sale_in_register', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_table('sales')
    # ### end Alembic commands ###
